### ISSUE TITLE
analytics.js file path relativeness causing 404

### ISSUE THREAD

**Issue by NeilujD** [StartPolymer/start-google-analytics-tracker#4]
The analytics file path should be absolute instead of relative.
My problem is that I get a 404 requesting the file because the request url is wrong when the actual navigator url isn't the root url.
By the way, it happens using Polymer carbon-route elements.
I think it should be better replacing `scripts/analytics.js` by `/scripts/analytics.js`.

**Comment by JosefJezek** [comment]
Hi, this element is deprecated, use analytics.js in index.html

https://github.com/StartPolymer/progressive-web-app-template/blob/master/index.html#L49
