### ISSUE TITLE
Artificially low bounce rate

### ISSUE THREAD

**Issue by Boscop** [StartPolymer/start-google-analytics-tracker#6]
I checked my page in Google Tag Assistant by recording all the track events that fire. I get this warning:
> Warning: This page has two interaction hits within a short time window. The page might have two hits that always fire on page load, which can cause an artificially low bounce rate.

This also happens when I only load the page once!
Because it first tracks an event for path '/' (when the element is instantiated) before tracking the real page path of the page that was loaded (e.g. '/my-profile'). Btw, I'm using page.js for routing.

When I remove all my track event fire calls, it still tracks the first '/' on page refresh (of page '/my-profile'), and here you can see that it indeed sends a page track event when the element is created:
https://github.com/StartPolymer/start-google-analytics-tracker/blob/master/start-google-analytics-tracker.html#L60
Why is this done?

If possible, I'd prefer to not send this event when the element is loaded so that the bounce rate is not artificially low.

Edit:
I just tested it with that line commented out and I don't get that warning anymore, only the real page track event for '/my-profile'.

**Comment by JosefJezek** [comment]
Hi, this element is deprecated, use analytics.js in index.html

https://github.com/StartPolymer/progressive-web-app-template/blob/master/index.html#L49
